<!--
 * @Author: liming
 * @Date: 2022-01-16 14:24:33
 * @LastEditTime: 2022-01-16 19:02:38
 * @FilePath: \02-代码手敲\day03\01-基本结构.html
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        function MyPromise(fn) {
            //promise的状态
            this.promiseState = 'pending';
            //promise的值
            this.promiseResult = undefined
            this.catchCallback = undefined;
            var _this = this;
            //console.log(_this, '_this');
            //存储当前的上下文对象

            //定义一个函数对象，用来注册then中的callback
            this.thenCallback = undefined;

            //TODO:resolve封装
            var resolve = function(value) {
                //console.log(value, 'value');
                //console.log(this, '上下文对象'); //window
                //更改promise的状态和值
                if (_this.promiseState == 'pending') {
                    //如果原始状态是pending的话，才改变它的状态，这样确保状态只会变一次(reject同理)
                    // console.log('resolve执行');
                    _this.promiseState = 'fulfilled';
                    _this.promiseResult = value;
                    if (value instanceof MyPromise) {
                        value.then(function(res) {
                            console.log(res);
                            if (_this.thenCallback) {
                                //如果thenCallback存在，则执行它
                                _this.thenCallback(res);
                            }
                        })
                    } else {
                        //其他情况我们正常调用setTimeout
                        setTimeout(function() {
                            //通过setTimeout的方式，定义一个异步任务，它会在then后面输出
                            //在不支持promise对象的浏览器中，我们只能用setTimeout来实现异步任务
                            // console.log('我是异步任务');
                            if (_this.thenCallback) {
                                //如果thenCallback存在，则执行它
                                _this.thenCallback(value);
                            }
                        });
                    }

                }
            }


            //TODO:reject封装
            var reject = function(errValue) {
                if (_this.promiseState == 'pending') {
                    _this.promiseState = 'rejected';
                    _this.promiseResult = errValue;
                    setTimeout(function() {
                        //console.log(_this, '上下文对象');
                        if (_this.catchCallback) {
                            _this.catchCallback(errValue);
                        } else if (_this.thenCallback) {
                            _this.thenCallback(errValue);
                        } else {
                            throw ('catch is not defined')
                        }
                    })
                }
            }

            if (fn) {
                fn(resolve, reject);
            }
        }

        //定义原型对象上的then
        MyPromise.prototype.then = function(callback) {
            var _this = this;
            //把resolve的值塞到callback回调函数里
            //我们想通过resolve来触发then中的callback执行
            //console.log('then执行');
            return new MyPromise(function(resolve, reject) {
                //这样来使用then的链式调用
                _this.thenCallback = function(value) {
                    console.log(_this.promiseState, '_this.promiseState');
                    if (_this.promiseState == 'rejected') {
                        //注释：在使用链式调用的时候，可能第一个调用的不是catch,所以我们在做检测时，
                        //会借助then来将catch的信息向下传递
                        //所以我们检测到触发thenCallback的对象是reject的时候
                        //我们就继续调用下一个对象的reject
                        reject(value)
                    } else {
                        var res = callback(value);
                        // console.log(res, 'res');
                        if (res instanceof MyPromise && res.promiseState == 'rejected') {
                            res.catch(function(errValue) {
                                reject(errValue);
                            })
                        } else {
                            resolve(res)
                        }
                    }

                }
            })
        }

        //定义原型对象上的catch
        MyPromise.prototype.catch = function(callback) {
            var _this = this;
            return new MyPromise(function(resolve, reject) {
                _this.catchCallback = function(errValue) {
                    var res = callback(errValue)
                    resolve(res)
                }
            })
        }

        MyPromise.resolve = function(value) {
            //这样我们可以直接通过MyPromise.resolve(value)来快捷调用resolve
            return new MyPromise(function(resolve, reject) {
                resolve(value);
            })
        }

        MyPromise.reject = function(errValue) {
                return new MyPromise(function(resolve, reject) {
                    reject(errValue);
                })
            }
            //console.log('start');


        MyPromise.all = function(promiseArr) {
            let resArr = []
            return new MyPromise(function(resolve, reject) {
                promiseArr.forEach((item, index) => {
                    //console.log(item);
                    item.then(function(res) {
                        resArr[index] = res
                        var allResolve = promiseArr.every(_item => {
                            return _item.promiseState == 'fulfilled'
                        })
                        if (allResolve) {
                            resolve(resArr)
                        }
                    }).catch(function(err) {
                        reject(err)
                    })
                })
            })
        }


        MyPromise.race = function(promiseArr) {
            var end = false
            return new MyPromise(function(resolve, reject) {
                for (var i = 0; i < promiseArr.length; i++) {
                    (function(i) {
                        promiseArr[i].then(function(res) {
                            if (end == false) {
                                end = true
                                resolve(res)
                            }
                        }).catch(function(err) {
                            if (end == false) {
                                end = true
                                reject(err)
                            }
                        })
                    })(i)
                }
            })
        }

        
        let p1 = new MyPromise((resolve, reject) => {
            setTimeout(() => {
                resolve('第⼀个promise执⾏完毕')
            }, 1000)
        })
        let p2 = new MyPromise((resolve, reject) => {
            setTimeout(() => {
                resolve('第⼆个promise执⾏完毕')
            }, 2000)
        })
        let p3 = new MyPromise((resolve, reject) => {
            setTimeout(() => {
                resolve('第三个promise执⾏完毕')
            }, 3000)
        })
        MyPromise.all([p1, p3, p2]).then(res => {
            console.log(res)
        }).catch(function(err) {
            console.log(err)
        })

        //开始创建一个实例对象
        // var p = new MyPromise(function(resolve, reject) {
        //     //console.log('promise执行');
        //     // setTimeout(function() {
        //     //     //console.log('setTimeout执行');
        //     //     resolve('hello');
        //     // }, 1000);
        //     resolve(MyPromise.resolve('我是第一个promise的值'))
        //         // reject('错误的值')
        // });

        // p.then(function(res) {
        //     console.log(res);
        //     console.log('第1个then');
        //     return '1'
        // }).then(function(res) {
        //     console.log(res);
        //     console.log('第2个then');
        //     // return '2'
        //     return MyPromise.reject('中断它')
        // }).then(function(res) {
        //     console.log(res);
        //     console.log('第3个then');
        //     return '3'
        // }).catch(function(err) {
        //     console.log(err);
        //     console.log('catch执行');
        //     return 123;
        // })

        //console.log(p, 'ppppppxxxxxxxxxxx');
        //console.log(p1, 'ppppppxxxxxxxxxxx');

        //console.log(p, 'ppppppppppp');
        // var p = new MyPromise(function(resolve, reject) {
        //     // console.log('promise实例化',resolve,reject);
        //     // resolve('我是promise的值~~~~~');
        //     //由于resolve是直接调用的，而不是使用p对象调用的，所以this是window
        //     //通过resolve来触发了then的执行
        //     setTimeout(function() {
        //         // resolve('我是2秒后prmise的值')
        //         resolve()
        //     },1000)

        // })

        //console.log(p, 'promise实例对象');

        // p.then(function(res) {
        //     //console.log(res, 'then里面的res1');
        //     console.log('第一个then执行');
        //     return new MyPromise((resolve) => {
        //             setTimeout(function() {
        //                 resolve()
        //             }, 1000)
        //         })
        //         // return 123;
        // }).then(function(res) {
        //     console.log(res, 'then里面的res2');
        //     console.log('第二个then执行');
        //     return new MyPromise((resolve) => {
        //         setTimeout(function() {
        //             resolve()
        //         }, 1000)
        //     })
        // }).then(function(res) {
        //     console.log(res, 'then里面的res3');
        //     console.log('第三个then执行');
        //     return MyPromise.resolve('我是promise的值');
        // }).then(function(res) {
        //     console.log(res, 'then里面的res4');
        //     console.log('第4个then执行');
        // });

        //p.then(xxx),里面的xxx是一个函数

        //console.log(p1, 'p1'); //undefined 说明我们的then不能链式调用
        //console.log('end');
    </script>

</body>

</html>