<!--
 * @Author: liming
 * @Date: 2021-08-12 01:02:40
 * @LastEditTime: 2021-08-12 01:06:53
 * @FilePath: \01-Promise★\04-一些文章解析Promise\01-Promise用法小结\代码手敲\06-catch的用法.html
-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      // 函数定义
      function promiseClick() {
        let p = new Promise((resolve, reject) => {
          setTimeout(() => {
            let num = Math.ceil(Math.random() * 20);
            console.log("随机数生成的值：" + num);
            if (num <= 10) {
              resolve(num);
            } else {
              reject("数字大于10，不予采纳，执行失败回调");
            }
          }, 1000);
        });
        //不写return会报错
        //Uncaught TypeError: Cannot read property 'then' of undefined
        return p;
        //   这句话必须要写！！！！！！！！
      }

      promiseClick()
        .then((data) => {
          console.log("resolved成功回调");
          console.log("成功回调接受的值：", data);
        })
        .catch((reason, data) => {
          console.log("catch到rejected失败回调");
          console.log("catch失败执行回调抛出失败原因：", reason);
          console.log("data", data);   //data undefined
        });
    </script>
  </body>
</html>
